#!/usr/bin/env python3
#----------------------------------------------------------------------------
#          _    _           Family:    aRVern System IPs
#         / \__/ \          Module:    gen_rtl_params
#        /   /\   \         --------------------------------------------
#    ===/   /=========      Copyright: (c) 2026, aRVern-dev
#      /   / RV \   \       Contact:   arvernsilicon@gmail.com
#     /___/______\___\      GitHub:    https://github.com/Arvern-Silicon
#
# SPDX-License-Identifier: BSD-3-Clause
# Full license text is available in the LICENSE file at the repository root.
#----------------------------------------------------------------------------
# File Name          : gen_rtl_params.py
# Module Description : Generate rtl_params.tcl from sim/rtl_sim/run/run_config.json; supports per-config sweep mode.
#----------------------------------------------------------------------------

"""
Generate RTL parameters TCL file from run_config.json

This script reads the run_config.json from the simulation directory and
extracts the default RTL parameter values to generate a TCL file that can
be sourced during synthesis.

Usage:
    python3 gen_rtl_params.py [--config PATH] [--output PATH]
"""

import json
import argparse
import sys
from pathlib import Path

# Share the sweep-config generator with the sim side so synthesis sweeps
# exercise the IDENTICAL 39-config set as `./run_all -rtl_sweep` and
# `run_lint --sweep`. Single source of truth: sim/rtl_sim/bin/rtl_sweep_configs.py
_SIM_BIN = (Path(__file__).parent / '..' / '..' / 'sim' / 'rtl_sim' / 'bin').resolve()
sys.path.insert(0, str(_SIM_BIN))
from rtl_sweep_configs import (generate_configs, sweepable_params, resolve_persona, PERSONAS,  # noqa: E402
                                print_sweep_list)


def parse_run_config(config_path):
    """Parse run_config.json and extract RTL parameters."""
    try:
        # JSON is defined as UTF-8; open explicitly so the parse does not
        # depend on the locale's default codec (Python 3.6 in the synthesis
        # Docker defaults to ASCII and chokes on any non-ASCII byte).
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except FileNotFoundError:
        print(f"Error: Config file not found: {config_path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {config_path}: {e}", file=sys.stderr)
        sys.exit(1)

    if 'rtl_config' not in config:
        print("Error: 'rtl_config' section not found in config file", file=sys.stderr)
        sys.exit(1)

    return config['rtl_config']


def generate_tcl(rtl_config, output_path, overrides=None):
    """Generate TCL file with parameter settings.

    overrides: optional {param_name: value} dict (from --rtl-config N). Any
    listed parameter takes its sweep value instead of run_config.json's
    'default', and the generated TCL is annotated to flag the override.
    """
    overrides = overrides or {}

    lines = [
        "##############################################################################",
        "#                                                                            #",
        "#                    RTL PARAMETERS FROM run_config.json                     #",
        "#                                                                            #",
        "#  Auto-generated by gen_rtl_params.py                                       #",
        "#  DO NOT EDIT MANUALLY - Edit run_config.json instead                       #",
        "#                                                                            #",
        "##############################################################################",
        "",
        "# RTL Configuration Parameters",
        "# (Sweep overrides via --rtl-config N show '# sweep override, was X' lines.)",
        ""
    ]

    # Generate parameter assignments
    for param_name, param_info in sorted(rtl_config.items()):
        default_value = param_info['default']
        if param_name in overrides:
            value = overrides[param_name]
            is_overridden = True
        else:
            value = default_value
            is_overridden = False

        description = param_info.get('description', '')

        lines.append(f"# {description}")
        if is_overridden:
            lines.append(f"# (sweep override, run_config.json default={default_value})")
        lines.append(f"set RTL_PARAM_{param_name} {value}")
        lines.append("")

    # Generate elaborate command parameters as a single comma-separated string
    # DC Shell requires: -parameters "PARAM1=val1,PARAM2=val2,..."
    # NOT multiple -parameters options
    lines.append("# Build parameter string for elaborate command")
    lines.append("# Format: -parameters \"PARAM1=val1,PARAM2=val2,...\"")

    param_assignments = []
    for param_name in sorted(rtl_config.keys()):
        param_assignments.append(f"{param_name}=${{RTL_PARAM_{param_name}}}")

    lines.append(f"set ELABORATE_PARAMS \"-parameters \\\"{','.join(param_assignments)}\\\"\"")
    lines.append("")

    # Add summary comment
    lines.append("# Parameter Summary:")
    for param_name, param_info in sorted(rtl_config.items()):
        if 'synthesis' in param_info and param_info['synthesis'] != -1:
            value = param_info['synthesis']
            default_value = param_info['default']
            description = param_info.get('description', '')
            lines.append(f"#   {param_name:20s} = {str(value):>12s}  # {description} (synthesis override, default={default_value})")
        else:
            value = param_info['default']
            description = param_info.get('description', '')
            lines.append(f"#   {param_name:20s} = {str(value):>12s}  # {description}")
    lines.append("")

    # Write to file
    try:
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))
        print(f"Generated: {output_path}")
        print(f"Parameters configured: {len(rtl_config)}")
        if overrides:
            print(f"  ({len(overrides)} parameter(s) overridden by --rtl-config)")

        for param_name, param_info in sorted(rtl_config.items()):
            default_value = param_info['default']
            if param_name in overrides:
                print(f"  {param_name:20s} = {overrides[param_name]} (sweep override, default={default_value})")
            else:
                print(f"  {param_name:20s} = {default_value}")
    except IOError as e:
        print(f"Error: Cannot write to {output_path}: {e}", file=sys.stderr)
        sys.exit(1)


def apply_sweep_override(rtl_config, sweep_sel):
    """Return (label, overrides) for the requested sweep config.

    `sweep_sel` is a string accepted in two forms (string in both cases so
    the same argparse value handles both):

      * integer (e.g. "14")  -- 1-based index into the 'all' sweep set,
                                 same numbering as `./run_all -rtl_sweep`
                                 and `run_lint --sweep`.
      * persona name (e.g. "minimal" / "medium" / "full")
                              -- resolves via the PERSONAS table in
                                 bin/rtl_sweep_configs.py.

    The overrides dict is later passed to generate_tcl, which emits sweep
    values for those params while preserving the rtl_config 'default' for
    the annotation comment.
    """
    params = sweepable_params(rtl_config)
    persona_names = {lbl for lbl, _ in PERSONAS}
    if sweep_sel in persona_names:
        return resolve_persona(sweep_sel, params)
    # Otherwise treat as integer index into the 'all' sweep set
    try:
        sweep_idx = int(sweep_sel)
    except ValueError:
        print(f"Error: --rtl-config '{sweep_sel}' is neither an integer "
              f"nor a known persona ({sorted(persona_names)})",
              file=sys.stderr)
        sys.exit(1)
    _order, configs = generate_configs(params, 'all')
    total = len(configs)
    if not (1 <= sweep_idx <= total):
        print(f"Error: --rtl-config {sweep_idx} out of range (valid: 1..{total})",
              file=sys.stderr)
        sys.exit(1)
    label, overrides = configs[sweep_idx - 1]
    return label, overrides


def list_configs(rtl_config):
    """Print the sweep set with a header legend explaining default / corner /
    ofat / xprod categories, then '<idx>\\t<label>' lines."""
    _order, configs = generate_configs(sweepable_params(rtl_config), 'all')
    print_sweep_list(configs)


def main():
    parser = argparse.ArgumentParser(
        description='Generate RTL parameters TCL file from run_config.json'
    )
    parser.add_argument(
        '--config',
        default='../../sim/rtl_sim/run/run_config.json',
        help='Path to run_config.json (default: ../../sim/rtl_sim/run/run_config.json)'
    )
    parser.add_argument(
        '--output',
        default='./rtl_params.tcl',
        help='Output TCL file path (default: ./rtl_params.tcl)'
    )
    parser.add_argument(
        '--rtl-config', metavar='N_OR_NAME',
        help='Apply a sweep config. Accepts either a 1-based integer index '
             '(e.g. 14 — same numbering as `./run_all -rtl_sweep` and '
             '`run_lint --sweep`) or a persona name (minimal / medium / full '
             'from bin/rtl_sweep_configs.py:PERSONAS). Use --list-configs to '
             'see the numbered set.'
    )
    parser.add_argument(
        '--list-configs', action='store_true',
        help='Print the sweep set (one per line: "<idx>\\t<label>") and exit. '
             'Used by run_syn to drive a -rtl_sweep iteration.'
    )
    parser.add_argument(
        '--list-personas', action='store_true',
        help='Print persona names (one per line) and exit. Used by run_syn to '
             'validate -rtl_config <persona_name> entries upfront.'
    )

    args = parser.parse_args()

    # Resolve paths relative to script location
    script_dir = Path(__file__).parent
    config_path = (script_dir / args.config).resolve()
    output_path = (script_dir / args.output).resolve()

    rtl_config = parse_run_config(config_path)

    if args.list_configs:
        list_configs(rtl_config)
        return

    if args.list_personas:
        for name, _params in PERSONAS:
            print(name)
        return

    print(f"Reading config from: {config_path}")

    overrides = None
    if args.rtl_config is not None:
        label, overrides = apply_sweep_override(rtl_config, args.rtl_config)
        print(f"Applying sweep config {args.rtl_config} ({label}):")
        for k, v in sorted(overrides.items()):
            print(f"  {k:20s} = {v}")
        print()

    print(f"Writing TCL to: {output_path}")
    generate_tcl(rtl_config, output_path, overrides=overrides)


if __name__ == '__main__':
    main()
